[ 2024-04-28 23:35:21,036 ] 91 root - INFO - Starting all threads
[ 2024-04-28 23:35:21,036 ] 91 root - INFO - Starting all threads
[ 2024-04-28 23:35:21,037 ] 91 root - INFO - Meta: {'__module__': 'src.globals', '__doc__': '        Meta configs        ', 'keyword': 'Tosan', 'test_mode': False, 'debug_mode': True, 'onlyday': True, 'max_num_retry': 5, 'default_num_threads': 3, 'display_number': 50, 'main_phone_number_dash': '080-1583-0891', 'uc': True, 'headless': False, 'timeout': 900, '__dict__': <attribute '__dict__' of 'Meta' objects>, '__weakref__': <attribute '__weakref__' of 'Meta' objects>}
[ 2024-04-28 23:35:21,037 ] 91 root - INFO - Meta: {'__module__': 'src.globals', '__doc__': '        Meta configs        ', 'keyword': 'Tosan', 'test_mode': False, 'debug_mode': True, 'onlyday': True, 'max_num_retry': 5, 'default_num_threads': 3, 'display_number': 50, 'main_phone_number_dash': '080-1583-0891', 'uc': True, 'headless': False, 'timeout': 900, '__dict__': <attribute '__dict__' of 'Meta' objects>, '__weakref__': <attribute '__weakref__' of 'Meta' objects>}
[ 2024-04-28 23:35:21,037 ] 91 root - INFO - Number of dev accounts: 0
[ 2024-04-28 23:35:21,037 ] 91 root - INFO - Number of dev accounts: 0
[ 2024-04-28 23:35:21,037 ] 91 root - INFO - Test mode: False
[ 2024-04-28 23:35:21,037 ] 91 root - INFO - Test mode: False
[ 2024-04-28 23:35:21,041 ] 91 main_controller - INFO - Subprocess 0 started with trial number 0
[ 2024-04-28 23:35:21,041 ] 91 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: luthien5921@gmail.com, Password: aichi@5921
[ 2024-04-28 23:35:23,051 ] 91 root - INFO - Thread 0 started
[ 2024-04-28 23:35:23,051 ] 91 root - INFO - Thread 0 started
[ 2024-04-28 23:35:23,056 ] 91 main_controller - INFO - Subprocess 1 started with trial number 0
[ 2024-04-28 23:35:23,056 ] 91 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: luthien5921+shinsei1@gmail.com, Password: aichi@5921
[ 2024-04-28 23:35:23,639 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:24,660 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:25,066 ] 91 root - INFO - Thread 1 started
[ 2024-04-28 23:35:25,066 ] 91 root - INFO - Thread 1 started
[ 2024-04-28 23:35:25,077 ] 91 main_controller - INFO - Subprocess 2 started with trial number 0
[ 2024-04-28 23:35:25,078 ] 91 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: luthien5921+shinsei2@gmail.com, Password: aichi@5921
[ 2024-04-28 23:35:27,108 ] 91 root - INFO - Thread 2 started
[ 2024-04-28 23:35:27,108 ] 91 root - INFO - Thread 2 started
[ 2024-04-28 23:35:27,247 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:31,203 ] 91 luthien5921 - INFO - Opened login page
[ 2024-04-28 23:35:31,263 ] 91 luthien5921+shinsei1 - INFO - Opened login page
[ 2024-04-28 23:35:32,297 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:33,686 ] 91 luthien5921+shinsei2 - INFO - Opened login page
[ 2024-04-28 23:35:34,069 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:34,455 ] 91 main_controller - INFO - Subprocess 1 started with trial number 1
[ 2024-04-28 23:35:36,622 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:36,668 ] 91 main_controller - INFO - Subprocess 0 started with trial number 1
[ 2024-04-28 23:35:38,505 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:42,580 ] 91 luthien5921+shinsei1 - INFO - Opened login page
[ 2024-04-28 23:35:44,540 ] 91 luthien5921 - INFO - Opened login page
[ 2024-04-28 23:35:45,116 ] 91 luthien5921+shinsei2 - INFO - Logging in
[ 2024-04-28 23:35:45,123 ] 91 luthien5921+shinsei2 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-28 23:35:45,439 ] 91 luthien5921+shinsei2 - INFO - Logged in finished
[ 2024-04-28 23:35:45,439 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-28 23:35:45,570 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:45,687 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_28\23_35_20\screenshot_luthien5921+shinsei2.png
[ 2024-04-28 23:35:45,687 ] 91 main_controller - INFO - Finding forms
[ 2024-04-28 23:35:45,692 ] 91 luthien5921+shinsei2 - INFO - On main page
[ 2024-04-28 23:35:47,563 ] 91 luthien5921+shinsei2 - INFO - Search submitted
[ 2024-04-28 23:35:47,586 ] 91 luthien5921+shinsei2 - INFO - Collected 10 forms
[ 2024-04-28 23:35:47,716 ] 91 main_controller - INFO - Subprocess 0 started with trial number 2
[ 2024-04-28 23:35:47,887 ] 91 luthien5921+shinsei2 - INFO - Number of filtered forms left is: 10 form(s)
[ 2024-04-28 23:35:47,887 ] 91 luthien5921+shinsei2 - INFO - 05月13日(月) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月29日 07時30分 - 2024年05月09日 12時00分 - 95433 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95433 - True
[ 2024-04-28 23:35:47,888 ] 91 luthien5921+shinsei2 - INFO - 05月14日(火) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月29日 07時30分 - 2024年05月10日 12時00分 - 95435 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95435 - True
[ 2024-04-28 23:35:47,888 ] 91 luthien5921+shinsei2 - INFO - 05月15日(水) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月29日 07時30分 - 2024年05月13日 12時00分 - 95438 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95438 - True
[ 2024-04-28 23:35:47,889 ] 91 luthien5921+shinsei2 - INFO - 05月16日(木) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月29日 07時30分 - 2024年05月14日 12時00分 - 95440 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95440 - True
[ 2024-04-28 23:35:47,896 ] 91 luthien5921+shinsei2 - INFO - 05月17日(金) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月29日 07時30分 - 2024年05月15日 12時00分 - 95441 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95441 - True
[ 2024-04-28 23:35:47,897 ] 91 luthien5921+shinsei2 - INFO - 05月07日(火) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月22日 07時30分 - 2024年05月01日 12時00分 - 95425 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95425 - False
[ 2024-04-28 23:35:47,897 ] 91 luthien5921+shinsei2 - INFO - 05月08日(水) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月22日 07時30分 - 2024年05月02日 12時00分 - 95426 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95426 - False
[ 2024-04-28 23:35:47,898 ] 91 luthien5921+shinsei2 - INFO - 05月09日(木) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月22日 07時30分 - 2024年05月07日 12時00分 - 95428 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95428 - False
[ 2024-04-28 23:35:47,898 ] 91 luthien5921+shinsei2 - INFO - 05月10日(金) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月22日 07時30分 - 2024年05月08日 12時00分 - 95430 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95430 - False
[ 2024-04-28 23:35:47,898 ] 91 luthien5921+shinsei2 - INFO - 05月02日(木) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月15日 07時30分 - 2024年04月30日 12時00分 - 95424 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95424 - False
[ 2024-04-28 23:35:47,899 ] 91 main_controller - INFO - Found 10 form(s)
[ 2024-04-28 23:35:47,900 ] 91 main_controller - INFO - Customers: None
[ 2024-04-28 23:35:47,900 ] 91 luthien5921+shinsei2 - INFO - Accessing form, template sequence: 95430
[ 2024-04-28 23:35:47,901 ] 91 luthien5921+shinsei2 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95430
[ 2024-04-28 23:35:48,898 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:50,284 ] 91 luthien5921+shinsei1 - INFO - Logging in
[ 2024-04-28 23:35:50,296 ] 91 luthien5921+shinsei1 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-28 23:35:50,617 ] 91 luthien5921+shinsei1 - INFO - Logged in finished
[ 2024-04-28 23:35:50,618 ] 91 main_controller - INFO - Logged in successfully
[ 2024-04-28 23:35:50,917 ] 91 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_28\23_35_20\screenshot_luthien5921+shinsei1.png
[ 2024-04-28 23:35:50,918 ] 91 main_controller - INFO - Finding forms
[ 2024-04-28 23:35:50,924 ] 91 luthien5921+shinsei1 - INFO - On main page
[ 2024-04-28 23:35:52,995 ] 91 luthien5921+shinsei1 - INFO - Search submitted
[ 2024-04-28 23:35:53,013 ] 91 luthien5921+shinsei1 - INFO - Collected 10 forms
[ 2024-04-28 23:35:53,261 ] 91 luthien5921+shinsei1 - INFO - Number of filtered forms left is: 10 form(s)
[ 2024-04-28 23:35:53,261 ] 91 luthien5921+shinsei1 - INFO - 05月13日(月) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月29日 07時30分 - 2024年05月09日 12時00分 - 95433 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95433 - True
[ 2024-04-28 23:35:53,261 ] 91 luthien5921+shinsei1 - INFO - 05月14日(火) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月29日 07時30分 - 2024年05月10日 12時00分 - 95435 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95435 - True
[ 2024-04-28 23:35:53,262 ] 91 luthien5921+shinsei1 - INFO - 05月15日(水) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月29日 07時30分 - 2024年05月13日 12時00分 - 95438 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95438 - True
[ 2024-04-28 23:35:53,262 ] 91 luthien5921+shinsei1 - INFO - 05月16日(木) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月29日 07時30分 - 2024年05月14日 12時00分 - 95440 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95440 - True
[ 2024-04-28 23:35:53,263 ] 91 luthien5921+shinsei1 - INFO - 05月17日(金) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月29日 07時30分 - 2024年05月15日 12時00分 - 95441 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95441 - True
[ 2024-04-28 23:35:53,263 ] 91 luthien5921+shinsei1 - INFO - 05月07日(火) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月22日 07時30分 - 2024年05月01日 12時00分 - 95425 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95425 - False
[ 2024-04-28 23:35:53,264 ] 91 luthien5921+shinsei1 - INFO - 05月08日(水) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月22日 07時30分 - 2024年05月02日 12時00分 - 95426 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95426 - False
[ 2024-04-28 23:35:53,273 ] 91 luthien5921+shinsei1 - INFO - 05月09日(木) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月22日 07時30分 - 2024年05月07日 12時00分 - 95428 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95428 - False
[ 2024-04-28 23:35:53,273 ] 91 luthien5921+shinsei1 - INFO - 05月10日(金) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月22日 07時30分 - 2024年05月08日 12時00分 - 95430 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95430 - False
[ 2024-04-28 23:35:53,274 ] 91 luthien5921+shinsei1 - INFO - 05月02日(木) 13:30[東三]外国免許切替一次審査 Tosan Exchanging Foreign Driver's License 1st Exam -  - 2024年04月15日 07時30分 - 2024年04月30日 12時00分 - 95424 - https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95424 - False
[ 2024-04-28 23:35:53,274 ] 91 main_controller - INFO - Found 10 form(s)
[ 2024-04-28 23:35:53,274 ] 91 main_controller - INFO - Customers: None
[ 2024-04-28 23:35:53,275 ] 91 luthien5921+shinsei1 - INFO - Accessing form, template sequence: 95425
[ 2024-04-28 23:35:53,275 ] 91 luthien5921+shinsei1 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95425
[ 2024-04-28 23:35:53,961 ] 91 luthien5921+shinsei2 - INFO - Accessed form successfully
[ 2024-04-28 23:35:53,977 ] 91 luthien5921+shinsei2 - INFO - Form message: 大変申し訳ございません。申込数が上限に達した為、締め切らせていただきました。
[ 2024-04-28 23:35:53,978 ] 91 luthien5921+shinsei2 - INFO - Form is closed, template sequence: 95430
[ 2024-04-28 23:35:53,979 ] 91 main_controller - INFO - Form is closed, template sequence: 95430
[ 2024-04-28 23:35:53,980 ] 91 main_controller - INFO - Remaining form(s): 9
[ 2024-04-28 23:35:53,981 ] 91 luthien5921+shinsei2 - INFO - Accessing form, template sequence: 95441
[ 2024-04-28 23:35:53,981 ] 91 luthien5921+shinsei2 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95441
[ 2024-04-28 23:35:54,863 ] 91 luthien5921 - INFO - Opened login page
[ 2024-04-28 23:35:55,903 ] 79 main_controller - ERROR - Caught exception: sequence item 1: expected str instance, NoSuchElementException found
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 38, in login
    browser.find_element(By.ID, "userLoginForm.userId").send_keys(self.account.username)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="userLoginForm.userId"]"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6769EF922+3045234]
	(No symbol) [0x00007FF676693652]
	(No symbol) [0x00007FF676557564]
	(No symbol) [0x00007FF6765A5F9D]
	(No symbol) [0x00007FF6765A606C]
	(No symbol) [0x00007FF6765EBDD7]
	(No symbol) [0x00007FF6765C9DEF]
	(No symbol) [0x00007FF6765E91C4]
	(No symbol) [0x00007FF6765C9B53]
	(No symbol) [0x00007FF67659813C]
	(No symbol) [0x00007FF676598D71]
	GetHandleVerifier [0x00007FF676A1E89D+3237613]
	GetHandleVerifier [0x00007FF676A60BA7+3508727]
	GetHandleVerifier [0x00007FF676A5976F+3478975]
	GetHandleVerifier [0x00007FF6767CF1C6+815126]
	(No symbol) [0x00007FF67669ED0F]
	(No symbol) [0x00007FF676699854]
	(No symbol) [0x00007FF6766999E2]
	(No symbol) [0x00007FF67668A574]
	BaseThreadInitThunk [0x00007FFFFB45257D+29]
	RtlUserThreadStart [0x00007FFFFCEEAA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 58, in subprocess
    result = access.login(browser)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\access.py", line 51, in login
    self.logger.error("Failed to login", e)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 73, in error
    self._log(logging.ERROR, *msg)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\logs.py", line 90, in _log
    message = " ".join(msg)
TypeError: sequence item 1: expected str instance, NoSuchElementException found
[ 2024-04-28 23:35:58,124 ] 91 main_controller - INFO - Subprocess 0 started with trial number 3
[ 2024-04-28 23:35:59,114 ] 91 main_controller - INFO - Browser opened
[ 2024-04-28 23:35:59,198 ] 91 luthien5921+shinsei1 - INFO - Accessed form successfully
[ 2024-04-28 23:35:59,244 ] 91 luthien5921+shinsei1 - INFO - Form message: 大変申し訳ございません。申込数が上限に達した為、締め切らせていただきました。
[ 2024-04-28 23:35:59,246 ] 91 luthien5921+shinsei1 - INFO - Form is closed, template sequence: 95425
[ 2024-04-28 23:35:59,247 ] 91 main_controller - INFO - Form is closed, template sequence: 95425
[ 2024-04-28 23:35:59,247 ] 91 main_controller - INFO - Remaining form(s): 9
[ 2024-04-28 23:35:59,248 ] 91 luthien5921+shinsei1 - INFO - Accessing form, template sequence: 95441
[ 2024-04-28 23:35:59,249 ] 91 luthien5921+shinsei1 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=95441
[ 2024-04-28 23:35:59,817 ] 91 luthien5921+shinsei2 - INFO - Accessed form successfully
[ 2024-04-28 23:35:59,831 ] 91 luthien5921+shinsei2 - INFO - Form message: 申込期間ではありません。
[ 2024-04-28 23:35:59,831 ] 91 luthien5921+shinsei2 - INFO - Refreshing page to check availability trial number 1, template sequence: 95441
[ 2024-04-28 23:36:02,585 ] 91 luthien5921+shinsei2 - INFO - Form message: 申込期間ではありません。
[ 2024-04-28 23:36:02,586 ] 91 luthien5921+shinsei2 - INFO - Refreshing page to check availability trial number 2, template sequence: 95441
[ 2024-04-28 23:36:04,801 ] 91 luthien5921+shinsei2 - INFO - Form message: 申込期間ではありません。
[ 2024-04-28 23:36:04,802 ] 91 luthien5921+shinsei2 - INFO - Refreshing page to check availability trial number 3, template sequence: 95441
[ 2024-04-28 23:36:05,454 ] 91 luthien5921+shinsei1 - INFO - Accessed form successfully
[ 2024-04-28 23:36:05,466 ] 91 luthien5921+shinsei1 - INFO - Form message: 申込期間ではありません。
[ 2024-04-28 23:36:05,467 ] 91 luthien5921+shinsei1 - INFO - Refreshing page to check availability trial number 1, template sequence: 95441
[ 2024-04-28 23:36:07,508 ] 91 luthien5921+shinsei2 - INFO - Form message: 申込期間ではありません。
[ 2024-04-28 23:36:07,509 ] 91 luthien5921+shinsei2 - INFO - Refreshing page to check availability trial number 4, template sequence: 95441
[ 2024-04-28 23:36:07,515 ] 91 luthien5921+shinsei1 - INFO - Form message: 申込期間ではありません。
[ 2024-04-28 23:36:07,516 ] 91 luthien5921+shinsei1 - INFO - Refreshing page to check availability trial number 2, template sequence: 95441
[ 2024-04-28 23:36:09,261 ] 91 luthien5921+shinsei2 - INFO - Form message: 申込期間ではありません。
[ 2024-04-28 23:36:09,262 ] 91 luthien5921+shinsei2 - INFO - Refreshing page to check availability trial number 5, template sequence: 95441
[ 2024-04-28 23:36:09,469 ] 91 luthien5921+shinsei1 - INFO - Form message: 申込期間ではありません。
[ 2024-04-28 23:36:09,470 ] 91 luthien5921+shinsei1 - INFO - Refreshing page to check availability trial number 3, template sequence: 95441
