[ 2024-04-16 04:35:59,267 ] 94 root - INFO - Starting all threads
[ 2024-04-16 04:35:59,267 ] 94 root - INFO - Starting all threads
[ 2024-04-16 04:35:59,267 ] 94 root - INFO - Meta: {'__module__': 'src.globals', '__doc__': '        Meta configs        ', 'keyword': 'gen', 'test_mode': True, 'default_num_threads': 1, 'display_number': 50, 'main_phone_number_hash': '080-1583-0891', 'uc': True, 'headless': False, '__dict__': <attribute '__dict__' of 'Meta' objects>, '__weakref__': <attribute '__weakref__' of 'Meta' objects>}
[ 2024-04-16 04:35:59,267 ] 94 root - INFO - Meta: {'__module__': 'src.globals', '__doc__': '        Meta configs        ', 'keyword': 'gen', 'test_mode': True, 'default_num_threads': 1, 'display_number': 50, 'main_phone_number_hash': '080-1583-0891', 'uc': True, 'headless': False, '__dict__': <attribute '__dict__' of 'Meta' objects>, '__weakref__': <attribute '__weakref__' of 'Meta' objects>}
[ 2024-04-16 04:35:59,267 ] 94 root - INFO - Number of dev accounts: 1
[ 2024-04-16 04:35:59,267 ] 94 root - INFO - Number of dev accounts: 1
[ 2024-04-16 04:35:59,269 ] 94 main_controller - ERROR - Account is a dictionary, convert to Account object: Username: luthien5921@gmail.com, Password: aichi@5921
[ 2024-04-16 04:36:01,296 ] 94 root - INFO - Thread 0 started
[ 2024-04-16 04:36:01,296 ] 94 root - INFO - Thread 0 started
[ 2024-04-16 04:36:01,926 ] 94 main_controller - INFO - Browser opened
[ 2024-04-16 04:36:07,468 ] 94 luthien5921 - INFO - Opened login page
[ 2024-04-16 04:36:10,752 ] 94 luthien5921 - INFO - Logging in
[ 2024-04-16 04:36:10,756 ] 94 luthien5921 - INFO - Current url: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_initDisplay
[ 2024-04-16 04:36:11,071 ] 94 luthien5921 - INFO - Logged in finished
[ 2024-04-16 04:36:11,071 ] 94 main_controller - INFO - Logged in successfully
[ 2024-04-16 04:36:11,310 ] 94 main_controller - INFO - Screenshot saved to C:\Users\USER\Projects\AichiTool\AichiSelenium\logs\2024_04_16\04_35_58\screenshot_luthien5921.png
[ 2024-04-16 04:36:11,310 ] 94 main_controller - INFO - Finding forms
[ 2024-04-16 04:36:11,314 ] 94 luthien5921 - INFO - On main page
[ 2024-04-16 04:36:13,050 ] 94 luthien5921 - INFO - Search submitted
[ 2024-04-16 04:36:13,069 ] 94 luthien5921 - INFO - Collected 4 forms
[ 2024-04-16 04:36:13,099 ] 94 luthien5921 - INFO - Parsed data: title: 【04月30日(火)】[東三] 運転免許学科試験〈原付のみ　初回・再受験者／日本語・ポルトガル語・英語受験者に限る＞gen, status: 受付開始日時, start_date: 2024年03月30日 07時30分, end_date: 2024年04月25日 12時00分, template_seq: 90551
[ 2024-04-16 04:36:13,100 ] 94 luthien5921 - INFO - Parsed data: title: 【04月30日(火)】[東三] 運転免許学科試験〈原付のみ　初回・再受験者／日本語・ポルトガル語・英語受験者に限る＞gen, status: 受付開始日時, start_date: 2024年03月30日 07時30分, end_date: 2024年04月25日 12時00分, template_seq: 90551
[ 2024-04-16 04:36:13,136 ] 94 luthien5921 - INFO - Parsed data: title: 【04月25日(木)】[東三] 運転免許学科試験〈原付のみ　初回・再受験者／日本語・ベトナム語・中国語受験者に限る＞gen, status: 受付開始日時, start_date: 2024年03月25日 07時30分, end_date: 2024年04月23日 12時00分, template_seq: 90550
[ 2024-04-16 04:36:13,136 ] 94 luthien5921 - INFO - Parsed data: title: 【04月25日(木)】[東三] 運転免許学科試験〈原付のみ　初回・再受験者／日本語・ベトナム語・中国語受験者に限る＞gen, status: 受付開始日時, start_date: 2024年03月25日 07時30分, end_date: 2024年04月23日 12時00分, template_seq: 90550
[ 2024-04-16 04:36:13,161 ] 94 luthien5921 - INFO - Parsed data: title: 【04月23日(火)】[東三] 運転免許学科試験〈原付のみ　初回・再受験者／日本語・ポルトガル語・英語受験者に限る＞gen, status: 受付開始日時, start_date: 2024年03月23日 07時30分, end_date: 2024年04月19日 12時00分, template_seq: 90549
[ 2024-04-16 04:36:13,162 ] 94 luthien5921 - INFO - Parsed data: title: 【04月23日(火)】[東三] 運転免許学科試験〈原付のみ　初回・再受験者／日本語・ポルトガル語・英語受験者に限る＞gen, status: 受付開始日時, start_date: 2024年03月23日 07時30分, end_date: 2024年04月19日 12時00分, template_seq: 90549
[ 2024-04-16 04:36:13,192 ] 94 luthien5921 - INFO - Parsed data: title: 【04月18日(木)】[東三] 運転免許学科試験〈原付のみ　初回・再受験者／日本語・ベトナム語・中国語受験者に限る＞gen, status: None, start_date: 2024年03月18日 07時30分, end_date: 2024年04月16日 12時00分, template_seq: 90548
[ 2024-04-16 04:36:13,193 ] 94 luthien5921 - INFO - Parsed data: title: 【04月18日(木)】[東三] 運転免許学科試験〈原付のみ　初回・再受験者／日本語・ベトナム語・中国語受験者に限る＞gen, status: None, start_date: 2024年03月18日 07時30分, end_date: 2024年04月16日 12時00分, template_seq: 90548
[ 2024-04-16 04:36:13,194 ] 94 luthien5921 - INFO - Number of filtered forms left is: 4 form(s)
[ 2024-04-16 04:36:13,194 ] 94 main_controller - INFO - Found 4 form(s)
[ 2024-04-16 04:36:13,196 ] 94 luthien5921 - INFO - Accessing form, template sequence: 90548
[ 2024-04-16 04:36:13,196 ] 94 luthien5921 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=90548
[ 2024-04-16 04:36:18,869 ] 94 luthien5921 - INFO - Form message: 大変申し訳ございません。申込数が上限に達した為、締め切らせていただきました。
[ 2024-04-16 04:36:18,870 ] 94 luthien5921 - INFO - Form is closed, template sequence: 90548
[ 2024-04-16 04:36:18,871 ] 94 main_controller - INFO - Form is closed, template sequence: 90548
[ 2024-04-16 04:36:18,871 ] 94 main_controller - INFO - Remaining form(s): 3
[ 2024-04-16 04:36:18,871 ] 94 luthien5921 - INFO - Accessing form, template sequence: 90549
[ 2024-04-16 04:36:18,871 ] 94 luthien5921 - INFO - Form URL: https://www.shinsei.e-aichi.jp/pref-aichi-police-u/offer/offerList_detailTop?tempSeq=90549
[ 2024-04-16 04:36:24,410 ] 82 luthien5921 - ERROR - Failed to get form message, maybe form is available
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 109, in get_form_message
    message = browser.find_element(By.XPATH, "/html/body/main/div/form/div[3]/strong/ul/li/span/strong").text
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\seleniumbase\core\sb_driver.py", line 20, in find_element
    return self.driver.default_find_element(by=by, value=value)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/main/div/form/div[3]/strong/ul/li/span/strong"}
  (Session info: chrome=123.0.6312.107); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF770D87032+63090]
	(No symbol) [0x00007FF770CF2C82]
	(No symbol) [0x00007FF770B8EC65]
	(No symbol) [0x00007FF770BD499D]
	(No symbol) [0x00007FF770BD4ADC]
	(No symbol) [0x00007FF770C15B37]
	(No symbol) [0x00007FF770BF701F]
	(No symbol) [0x00007FF770C13412]
	(No symbol) [0x00007FF770BF6D83]
	(No symbol) [0x00007FF770BC83A8]
	(No symbol) [0x00007FF770BC9441]
	GetHandleVerifier [0x00007FF7711825AD+4238317]
	GetHandleVerifier [0x00007FF7711BF70D+4488525]
	GetHandleVerifier [0x00007FF7711B79EF+4456495]
	GetHandleVerifier [0x00007FF770E60576+953270]
	(No symbol) [0x00007FF770CFE54F]
	(No symbol) [0x00007FF770CF9224]
	(No symbol) [0x00007FF770CF935B]
	(No symbol) [0x00007FF770CE9B94]
	BaseThreadInitThunk [0x00007FFDC2F1257D+29]
	RtlUserThreadStart [0x00007FFDC3E0AA48+40]

[ 2024-04-16 04:36:24,412 ] 94 luthien5921 - INFO - Form is available, template sequence: 90549
[ 2024-04-16 04:36:24,412 ] 94 luthien5921 - INFO - Filling form, template sequence: 90549
[ 2024-04-16 04:36:25,673 ] 94 luthien5921 - INFO - Clicked continue button
[ 2024-04-16 04:36:25,750 ] 94 luthien5921 - INFO - Filled input: item[0].textData2 by name, value: Hai
[ 2024-04-16 04:36:25,883 ] 94 luthien5921 - INFO - Filled input: item[0].textData by name, value: Nguyen
[ 2024-04-16 04:36:26,000 ] 94 luthien5921 - INFO - Filled input: item[2].textData by name, value: 19931112
[ 2024-04-16 04:36:26,080 ] 94 luthien5921 - INFO - Filled input: item[4].textData by name, value: 0809998888
[ 2024-04-16 04:36:26,147 ] 94 luthien5921 - INFO - Filled input: item[5].textData by name, value: Shogun
[ 2024-04-16 04:36:26,203 ] 94 luthien5921 - INFO - Check checkbox: /html/body/form/main/div/div[4]/dl[8]/dd/fieldset/p/label/span by xpath
[ 2024-04-16 04:36:28,963 ] 82 main_controller - ERROR - Caught exception: argument of type 'UnexpectedAlertPresentException' is not iterable
Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 89, in fill
    page_src = browser.page_source
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\seleniumbase\undetected\__init__.py", line 326, in __getattribute__
    return super().__getattribute__(item)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)["value"]
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\anaconda3\envs\aichi\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 228, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 整理番号・パスワードをメモなどにお控えいただくか、
当ページをファイルに保存、または印刷して保管してください。
整理番号・パスワードを紛失すると
申込内容を照会できなくなる可能性がございます。
Message: unexpected alert open: {Alert text : 整理番号・パスワードをメモなどにお控えいただくか、
当ページをファイルに保存、または印刷して保管してください。
整理番号・パスワードを紛失すると
申込内容を照会できなくなる可能性がございます。}
  (Session info: chrome=123.0.6312.107)
Stacktrace:
	GetHandleVerifier [0x00007FF770D87032+63090]
	(No symbol) [0x00007FF770CF2C82]
	(No symbol) [0x00007FF770B8EC65]
	(No symbol) [0x00007FF770C13B70]
	(No symbol) [0x00007FF770BF6D83]
	(No symbol) [0x00007FF770BC83A8]
	(No symbol) [0x00007FF770BC9441]
	GetHandleVerifier [0x00007FF7711825AD+4238317]
	GetHandleVerifier [0x00007FF7711BF70D+4488525]
	GetHandleVerifier [0x00007FF7711B79EF+4456495]
	GetHandleVerifier [0x00007FF770E60576+953270]
	(No symbol) [0x00007FF770CFE54F]
	(No symbol) [0x00007FF770CF9224]
	(No symbol) [0x00007FF770CF935B]
	(No symbol) [0x00007FF770CE9B94]
	BaseThreadInitThunk [0x00007FFDC2F1257D+29]
	RtlUserThreadStart [0x00007FFDC3E0AA48+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\main_controller.py", line 75, in subprocess
    filler.fill(browser, form_info)
  File "C:\Users\USER\Projects\AichiTool\AichiSelenium\src\controllers\filler.py", line 100, in fill
    if EndMessage.DEFENSE_ERROR in e:
TypeError: argument of type 'UnexpectedAlertPresentException' is not iterable
[ 2024-04-16 04:36:28,965 ] 94 main_controller - INFO - Closing browser
[ 2024-04-16 04:36:31,184 ] 94 main_controller - INFO - Browser closed
[ 2024-04-16 04:36:31,184 ] 94 root - INFO - All threads are done
[ 2024-04-16 04:36:31,184 ] 94 root - INFO - All threads are done
